/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2016-05-06-e96f49d"
#endif /* AVUTIL_FFVERSION_H */
