/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sjtu_nerdtv_smt_player_jni_SmtNativeApi */

#ifndef _Included_org_sjtu_nerdtv_smt_player_jni_SmtNativeApi
#define _Included_org_sjtu_nerdtv_smt_player_jni_SmtNativeApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_sjtu_nerdtv_smt_player_jni_SmtNativeApi
 * Method:    getSmt
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_sjtu_nerdtv_smt_player_jni_SmtNativeApi_getSmt
  (JNIEnv *, jclass);

/*
 * Class:     org_sjtu_nerdtv_smt_player_jni_SmtNativeApi
 * Method:    play
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_sjtu_nerdtv_smt_player_jni_SmtNativeApi_play
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
